[package]
name = "yew_sample"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive-new = "0.5.9"
getset = "0.1.2"
log = "0.4.14"
wasm-logger = "0.2.0"
yew = "0.19.3"
